package base;
public interface DegreeTests$0 extends base.F$2{
  default Object read$$hash$1(Object p0){
    var this$= this;
    var _aimpl$= (base.Tests$0)p0;
    return ((base.Tests$0)((base.Tests$0)((base.Tests$0)((base.Tests$0)((base.Tests$0)((base.Tests$0)((base.Tests$0)((base.Tests$0)((base.Tests$0)((base.Tests$0)((base.Tests$0)_aimpl$.imm$test$1(
((base.Float$0)((base.Radian$0)((base.Degree$0)((base.Opt$1)base.Degrees$0.instance.read$$hash$1(
base.Float$0Instance.instance(180.0d))).read$$bang$0(
)).imm$toRad$0(
)).read$$hash$0(
)).read$assertEq$1(
base.Math$0.instance.imm$pi$0(
)))).imm$test$1(
((base.Float$0)((base.Degree$0)((base.Degree$0)((base.Opt$1)base.Degrees$0.instance.read$$hash$1(
base.Float$0Instance.instance(360.0d))).read$$bang$0(
)).read$normalize$0(
)).read$$hash$0(
)).read$assertEq$1(
base.Float$0Instance.instance(0.0d)))).imm$test$1(
((base.Float$0)((base.Degree$0)((base.Degree$0)((base.Opt$1)base.Degrees$0.instance.read$$hash$1(
base.Float$0Instance.instance(-90.0d))).read$$bang$0(
)).read$normalize$0(
)).read$$hash$0(
)).read$assertEq$1(
base.Float$0Instance.instance(270.0d)))).imm$test$1(
((base.Float$0)((base.Degree$0)((base.Opt$1)base.Degrees$0.instance.read$$hash$1(
base.Float$0Instance.instance(0.0d))).read$$bang$0(
)).imm$sin$0(
)).read$assertEq$1(
base.Float$0Instance.instance(0.0d)))).imm$test$1(
((base.Float$0)((base.Degree$0)((base.Opt$1)base.Degrees$0.instance.read$$hash$1(
base.Float$0Instance.instance(90.0d))).read$$bang$0(
)).imm$sin$0(
)).read$assertEq$1(
base.Float$0Instance.instance(1.0d)))).imm$test$1(
base._FloatTest$0.instance.imm$closeTo$2(
((base.Degree$0)((base.Opt$1)base.Degrees$0.instance.read$$hash$1(
base.Float$0Instance.instance(180.0d))).read$$bang$0(
)).imm$sin$0(
),
base.Float$0Instance.instance(0.0d)))).imm$test$1(
((base.Float$0)((base.Degree$0)((base.Opt$1)base.Degrees$0.instance.read$$hash$1(
base.Float$0Instance.instance(270.0d))).read$$bang$0(
)).imm$sin$0(
)).read$assertEq$1(
base.Float$0Instance.instance(-1.0d)))).imm$test$1(
((base.Float$0)((base.Degree$0)((base.Opt$1)base.Degrees$0.instance.read$$hash$1(
base.Float$0Instance.instance(0.0d))).read$$bang$0(
)).imm$cos$0(
)).read$assertEq$1(
base.Float$0Instance.instance(1.0d)))).imm$test$1(
base._FloatTest$0.instance.imm$closeTo$2(
((base.Degree$0)((base.Opt$1)base.Degrees$0.instance.read$$hash$1(
base.Float$0Instance.instance(90.0d))).read$$bang$0(
)).imm$cos$0(
),
base.Float$0Instance.instance(0.0d)))).imm$test$1(
((base.Float$0)((base.Degree$0)((base.Opt$1)base.Degrees$0.instance.read$$hash$1(
base.Float$0Instance.instance(180.0d))).read$$bang$0(
)).imm$cos$0(
)).read$assertEq$1(
base.Float$0Instance.instance(-1.0d)))).imm$test$1(
base._FloatTest$0.instance.imm$closeTo$2(
((base.Degree$0)((base.Opt$1)base.Degrees$0.instance.read$$hash$1(
base.Float$0Instance.instance(270.0d))).read$$bang$0(
)).imm$cos$0(
),
base.Float$0Instance.instance(0.0d)))).imm$test$1(
((base.Bool$0)((base.Bool$0)((base.Bool$0)((base.Opt$1)base.Degrees$0.instance.read$$hash$1(
base.Math$0.instance.imm$nan$0(
))).read$isEmpty$0(
)).imm$$and$1(
((base.Opt$1)base.Degrees$0.instance.read$$hash$1(
base.Math$0.instance.imm$inf$0(
))).read$isEmpty$0(
))).imm$$and$1(
((base.Opt$1)base.Degrees$0.instance.read$$hash$1(
base.Math$0.instance.imm$negInf$0(
))).read$isEmpty$0(
))).imm$assertTrue$0(
));
  }
  DegreeTests$0 instance= new DegreeTests$0(){};}