package base;
public interface RadianTests$0 extends base.F$2{
  default Object read$$hash$1(Object p0){
    var this$= this;
    var _aimpl$= (base.Tests$0)p0;
    return ((base.Tests$0)((base.Tests$0)((base.Tests$0)((base.Tests$0)((base.Tests$0)((base.Tests$0)((base.Tests$0)((base.Tests$0)((base.Tests$0)((base.Tests$0)((base.Tests$0)((base.Tests$0)((base.Tests$0)_aimpl$.imm$test$1(
((base.Degree$0)((base.Radian$0)((base.Opt$1)base.Radians$0.instance.read$$hash$1(
base.Math$0.instance.imm$pi$0(
))).read$$bang$0(
)).imm$toDeg$0(
)).read$assertEq$1(
((base.Opt$1)base.Degrees$0.instance.read$$hash$1(
base.Float$0Instance.instance(180.0d))).read$$bang$0(
)))).imm$test$1(
((base.Float$0)((base.Radian$0)((base.Radian$0)((base.Opt$1)base.Radians$0.instance.read$$hash$1(
base.Math$0.instance.imm$tau$0(
))).read$$bang$0(
)).read$normalize$0(
)).read$$hash$0(
)).read$assertEq$1(
base.Float$0Instance.instance(0.0d)))).imm$test$1(
((base.Float$0)((base.Radian$0)((base.Radian$0)((base.Opt$1)base.Radians$0.instance.read$$hash$1(
((base.Float$0)base.Math$0.instance.imm$tau$0(
)).imm$$slash$1(
base.Float$0Instance.instance(-4.0d)))).read$$bang$0(
)).read$normalize$0(
)).read$$hash$0(
)).read$assertEq$1(
((base.Float$0)((base.Float$0)base.Math$0.instance.imm$tau$0(
)).imm$$star$1(
base.Float$0Instance.instance(3.0d))).imm$$slash$1(
base.Float$0Instance.instance(4.0d))))).imm$test$1(
base._FloatTest$0.instance.imm$closeTo$2(
((base.Radian$0)((base.Opt$1)base.Radians$0.instance.read$$hash$1(
base.Float$0Instance.instance(0.0d))).read$$bang$0(
)).imm$cos$0(
),
base.Float$0Instance.instance(1.0d)))).imm$test$1(
base._FloatTest$0.instance.imm$closeTo$2(
((base.Radian$0)((base.Opt$1)base.Radians$0.instance.read$$hash$1(
((base.Float$0)base.Math$0.instance.imm$pi$0(
)).imm$$slash$1(
base.Float$0Instance.instance(2.0d)))).read$$bang$0(
)).imm$cos$0(
),
base.Float$0Instance.instance(0.0d)))).imm$test$1(
base._FloatTest$0.instance.imm$closeTo$2(
((base.Radian$0)((base.Opt$1)base.Radians$0.instance.read$$hash$1(
base.Math$0.instance.imm$pi$0(
))).read$$bang$0(
)).imm$cos$0(
),
base.Float$0Instance.instance(-1.0d)))).imm$test$1(
base._FloatTest$0.instance.imm$closeTo$2(
((base.Radian$0)((base.Opt$1)base.Radians$0.instance.read$$hash$1(
((base.Float$0)((base.Float$0)base.Math$0.instance.imm$tau$0(
)).imm$$star$1(
base.Float$0Instance.instance(3.0d))).imm$$slash$1(
base.Float$0Instance.instance(4.0d)))).read$$bang$0(
)).imm$cos$0(
),
base.Float$0Instance.instance(0.0d)))).imm$test$1(
base._FloatTest$0.instance.imm$closeTo$2(
((base.Radian$0)((base.Opt$1)base.Radians$0.instance.read$$hash$1(
base.Float$0Instance.instance(0.0d))).read$$bang$0(
)).imm$tan$0(
),
base.Float$0Instance.instance(0.0d)))).imm$test$1(
base._FloatTest$0.instance.imm$closeTo$2(
((base.Radian$0)((base.Opt$1)base.Radians$0.instance.read$$hash$1(
((base.Float$0)base.Math$0.instance.imm$pi$0(
)).imm$$slash$1(
base.Float$0Instance.instance(4.0d)))).read$$bang$0(
)).imm$tan$0(
),
base.Float$0Instance.instance(1.0d)))).imm$test$1(
base._FloatTest$0.instance.imm$closeTo$2(
((base.Radian$0)((base.Opt$1)base.Radians$0.instance.read$$hash$1(
base.Math$0.instance.imm$pi$0(
))).read$$bang$0(
)).imm$tan$0(
),
base.Float$0Instance.instance(0.0d)))).imm$test$1(
base._FloatTest$0.instance.imm$closeTo$2(
((base.Radian$0)((base.Opt$1)base.Radians$0.instance.read$$hash$1(
((base.Float$0)((base.Float$0)base.Math$0.instance.imm$pi$0(
)).imm$$star$1(
base.Float$0Instance.instance(3.0d))).imm$$slash$1(
base.Float$0Instance.instance(4.0d)))).read$$bang$0(
)).imm$tan$0(
),
base.Float$0Instance.instance(-1.0d)))).imm$test$1(
((base.Bool$0)((base.Float$0)((base.Radian$0)((base.Opt$1)base.Radians$0.instance.read$$hash$1(
((base.Float$0)base.Math$0.instance.imm$pi$0(
)).imm$$slash$1(
base.Float$0Instance.instance(2.0d)))).read$$bang$0(
)).imm$tan$0(
)).read$$gt_eq$1(
base.Float$0Instance.instance(10.0d).imm$$star_star$1(
base.Float$0Instance.instance(10.0d)))).imm$assertTrue$0(
))).imm$test$1(
((base.Bool$0)((base.Float$0)((base.Radian$0)((base.Opt$1)base.Radians$0.instance.read$$hash$1(
((base.Float$0)((base.Float$0)base.Math$0.instance.imm$pi$0(
)).imm$$slash$1(
base.Float$0Instance.instance(2.0d))).imm$$plus$1(
base.Float$0Instance.instance(10.0d).imm$$star_star$1(
base.Float$0Instance.instance(-6.0d))))).read$$bang$0(
)).imm$tan$0(
)).read$$lt_eq$1(
base.Float$0Instance.instance(10.0d).imm$$star_star$1(
base.Float$0Instance.instance(10.0d)))).imm$assertTrue$0(
))).imm$test$1(
((base.Bool$0)((base.Bool$0)((base.Bool$0)((base.Opt$1)base.Radians$0.instance.read$$hash$1(
base.Math$0.instance.imm$nan$0(
))).read$isEmpty$0(
)).imm$$and$1(
((base.Opt$1)base.Radians$0.instance.read$$hash$1(
base.Math$0.instance.imm$inf$0(
))).read$isEmpty$0(
))).imm$$and$1(
((base.Opt$1)base.Radians$0.instance.read$$hash$1(
base.Math$0.instance.imm$negInf$0(
))).read$isEmpty$0(
))).imm$assertTrue$0(
));
  }
  RadianTests$0 instance= new RadianTests$0(){};}