package base;
public interface StrSepOps$0 extends base.F$2{
  default Object read$$hash$1(Object p0){
    var this$= this;
    var _aimpl$= (base.Tests$0)p0;
    return ((base.Tests$0)((base.Tests$0)((base.Tests$0)((base.Tests$0)((base.Tests$0)((base.Tests$0)((base.Tests$0)((base.Tests$0)((base.Tests$0)((base.Tests$0)((base.Tests$0)((base.Tests$0)((base.Tests$0)((base.Tests$0)((base.Tests$0)((base.Tests$0)((base.Tests$0)_aimpl$.imm$test$1(
((base.Nat$0)((base.Str$0)base.Str$0Instance.instance("a").imm$$or$1(
base.Str$0Instance.instance("b"))).imm$size$0(
)).read$assertEq$1(
base.Nat$0Instance.instance(3L)))).imm$test$1(
((base.Nat$0)((base.Str$0)((base.Str$0)base.Str$0Instance.instance("a").imm$$or$1(
base.Str$0Instance.instance("b"))).imm$$or$1(
base.Str$0Instance.instance("c"))).imm$size$0(
)).read$assertEq$1(
base.Nat$0Instance.instance(5L)))).imm$test$1(
((base.Nat$0)((base.Str$0)base.Str$0Instance.instance("").imm$$or$1(
base.Str$0Instance.instance("a"))).imm$size$0(
)).read$assertEq$1(
base.Nat$0Instance.instance(2L)))).imm$test$1(
((base.Nat$0)((base.Str$0)base.Str$0Instance.instance("a").imm$$or$1(
base.Str$0Instance.instance(""))).imm$size$0(
)).read$assertEq$1(
base.Nat$0Instance.instance(2L)))).imm$test$1(
((base.Nat$0)((base.Str$0)base.Str$0Instance.instance("a").imm$$or$0(
)).imm$size$0(
)).read$assertEq$1(
base.Nat$0Instance.instance(2L)))).imm$test$1(
((base.Str$0)base.Str$0Instance.instance("a").imm$$or$0(
)).read$assertEq$1(
base.Str$0Instance.instance("a").imm$$or$1(
base.Str$0Instance.instance(""))))).imm$test$1(
((base.Nat$0)((base.Str$0)((base.Str$0)base.Str$0Instance.instance("a").imm$$or$0(
)).imm$$or$1(
base.Str$0Instance.instance("b"))).imm$size$0(
)).read$assertEq$1(
base.Nat$0Instance.instance(4L)))).imm$test$1(
((base.Nat$0)((base.Str$0)base.Str$0Instance.instance("a").imm$$xor$1(
base.Str$0Instance.instance("b"))).imm$size$0(
)).read$assertEq$1(
base.Nat$0Instance.instance(3L)))).imm$test$1(
((base.Nat$0)((base.Str$0)((base.Str$0)base.Str$0Instance.instance("a").imm$$xor$1(
base.Str$0Instance.instance("b"))).imm$$xor$1(
base.Str$0Instance.instance("c"))).imm$size$0(
)).read$assertEq$1(
base.Nat$0Instance.instance(5L)))).imm$test$1(
((base.Nat$0)((base.Str$0)base.Str$0Instance.instance("").imm$$xor$1(
base.Str$0Instance.instance("a"))).imm$size$0(
)).read$assertEq$1(
base.Nat$0Instance.instance(2L)))).imm$test$1(
((base.Nat$0)((base.Str$0)base.Str$0Instance.instance("a").imm$$xor$1(
base.Str$0Instance.instance(""))).imm$size$0(
)).read$assertEq$1(
base.Nat$0Instance.instance(2L)))).imm$test$1(
((base.Nat$0)((base.Str$0)base.Str$0Instance.instance("a").imm$$xor$0(
)).imm$size$0(
)).read$assertEq$1(
base.Nat$0Instance.instance(2L)))).imm$test$1(
((base.Str$0)base.Str$0Instance.instance("a").imm$$xor$0(
)).read$assertEq$1(
base.Str$0Instance.instance("a").imm$$xor$1(
base.Str$0Instance.instance(""))))).imm$test$1(
((base.Nat$0)((base.Str$0)((base.Str$0)base.Str$0Instance.instance("a").imm$$xor$0(
)).imm$$xor$1(
base.Str$0Instance.instance("b"))).imm$size$0(
)).read$assertEq$1(
base.Nat$0Instance.instance(4L)))).imm$test$1(
((base.Nat$0)((base.Str$0)base.Str$0Instance.instance("a").imm$$or$1(
base.True$0.instance)).imm$size$0(
)).read$assertEq$1(
base.Nat$0Instance.instance(6L)))).imm$test$1(
((base.Nat$0)((base.Str$0)base.Str$0Instance.instance("a").imm$$xor$1(
base.True$0.instance)).imm$size$0(
)).read$assertEq$1(
base.Nat$0Instance.instance(6L)))).imm$test$1(
((base.Bool$0)((base.Str$0)base.Str$0Instance.instance("").imm$$or$1(
base.Str$0Instance.instance(""))).imm$isEmpty$0(
)).read$assertEq$1(
base.False$0.instance))).imm$test$1(
((base.Bool$0)((base.Str$0)base.Str$0Instance.instance("").imm$$xor$1(
base.Str$0Instance.instance(""))).imm$isEmpty$0(
)).read$assertEq$1(
base.False$0.instance));
  }
  StrSepOps$0 instance= new StrSepOps$0(){};}